appVersion: v1
kind      : deployment
metadata  : 
  name : flask-app
  labels : 
    app: flask-app
spec :
  replicas : 2
  selector : 
    matchlabels :
      app : flask
  template :
    metadata : 
      labels:
        app: nginx
    spec:
      conatiners :
      - name: flask
        image: venkatamunireddy/firstpythonapplication:new
        ports: 5000